package com.app.mirrorpage.ui;

import com.app.mirrorpage.app.framework.Funcoes;
import com.app.mirrorpage.app.framework.Log;
import com.app.mirrorpage.app.listener.Cliente_listener;
import com.app.mirrorpage.app.model.Tabela;
import com.app.mirrorpage.app.table.SyncAmbiente;
import com.app.mirrorpage.client.dto.CellChangeEvent;
import com.app.mirrorpage.client.dto.RowDeletedEvent;
import com.app.mirrorpage.client.dto.RowInsertedEvent;
import com.app.mirrorpage.client.dto.RowMoveEvent;
import com.app.mirrorpage.client.net.ApiClient;
import com.app.mirrorpage.client.net.SheetSocketClient;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URI;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

public class jInternal_tabela extends javax.swing.JInternalFrame {

    private int lockedRow = -1;
    private int lockedCol = -1;

    private int editingViewRow = -1;
    private int editingViewCol = -1;
    private int editingModelRow = -1;
    private int editingModelCol = -1;

    private Object oldCellValue = null;
    private int oldCellRow = -1;
    private int oldCellCol = -1;

    Cliente_listener listener;
    ApiClient api;
    private SheetSocketClient wsClient;
    private SyncAmbiente sync;

    String usuarioLogado;

    String csv_server;

    AtomicBoolean acao_line = new AtomicBoolean(true);

    public jInternal_tabela(DefaultTableModel model, ApiClient api, Cliente_listener listener, String csv_server, String usuarioLogado) {
        this.api = api;
        this.csv_server = csv_server;
        this.listener = listener;
        this.usuarioLogado = usuarioLogado;

        initComponents();

        this.sync = new SyncAmbiente(this, api, csv_server);

        tabela_news.setModel(model);
        tabela_news.setName("news");
        System.out.println("\nCsv - " + csv_server + "\n");

        Tabela.ajustarLarguraColuna(tabela_news);

        conectarWebSocket();

        setBorder(null);
        barra_titulo();
        edicao_celula();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_news = new javax.swing.JTable();

        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jScrollPane1.setBorder(null);

        tabela_news.setFont(new java.awt.Font("Globotipo Corporativa Textos", 1, 14)); // NOI18N
        tabela_news.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela_news.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabela_news.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabela_newsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabela_newsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_news);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        tabela_news.setSize(getSize());
    }//GEN-LAST:event_formComponentResized

    private void tabela_newsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_newsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            event_enter();
        }


    }//GEN-LAST:event_tabela_newsKeyReleased

    void event_enter() {
        // se ainda está em edição, ignora esse ENTER
        // (ele foi usado pra dar stopCellEditing no edicao_celula)
        if (tabela_news.isEditing()) {
            return;
        }

        int row = tabela_news.getSelectedRow();
        int col = tabela_news.getSelectedColumn();
        if (row < 0 || col < 0) {
            return;
        }

        int last_row = tabela_news.getRowCount() - 1;

        // VIEW -> MODEL para sincronizar com o servidor
        int modelRow = tabela_news.convertRowIndexToModel(row);
        int modelCol = tabela_news.convertColumnIndexToModel(col);

        Object valueObj = tabela_news.getModel().getValueAt(modelRow, modelCol);
        String value = (valueObj == null) ? "" : valueObj.toString();
        if (value.contains(";")) {
            value = value.replace(";", ",");
        }

        System.out.println("ENTER detectado em row=" + row + " col=" + col);

        if (col == 0) {
            if (value.equals("") || value == null) {
                restaurarValorAnteriorSeMesmaCelula(modelRow, modelCol);
                return;
            }
            if (isInt(value)) {
                int new_line = Integer.parseInt(value);
                move_line(row, col, new_line);
            } else {
                restaurarValorAnteriorSeMesmaCelula(modelRow, modelCol);
            }
            return;

        }

        // TEMPO (col 8 ou 9)
        if (col == 8 || col == 9) {
            System.out.println("Coluna " + col + " Identificada");
            sync.onCellEdit(modelRow, modelCol, value);
            in_tMat(row, col, true);        // usa VIEW pra calcular tMat
            return;
        }

        // ENTRADA DO JORNAL
        if (row == 0 && col == 13) {
            System.out.println("Entrada de Jornal Identificada");
            sync.onCellEdit(modelRow, modelCol, value);
            add_tempo_entrada(modelRow, modelCol);            // dentro dele já chama sync

            return;
        }

        // ENCERRAMENTO DO JORNAL (aqui você usou last_row, mas talvez seja penúltima)
        if (row == last_row && col == 13) {
            System.out.println("Encerramento de Jornal Identificada");
            sync.onCellEdit(modelRow, modelCol, value);
            add_tempo_encerramento(row, col);       // dentro dele já chama sync

            return;
        }

        // demais células: só sincroniza
        sync.onCellEdit(modelRow, modelCol, value);
    }

    public static boolean isInt(String s) {
        if (s == null) {
            return false;
        }
        s = s.trim();
        try {
            Integer.parseInt(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void tabela_newsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_newsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_INSERT) {
            Funcoes.acao_com_trava(() -> {
                tabela_news.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

                new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        Thread.sleep(300);
                        return null;
                    }

                    @Override
                    protected void done() {
                        try {
                            event_insert();
                            Log.registrarErro_noEx("[INSERT] - Linha inserida");
                        } finally {
                            acao_line.set(true); // 🔓 libera de novo
                            tabela_news.setCursor(Cursor.getDefaultCursor());
                            Log.registrarErro_noEx("[INSERT] - Linha não inserida");
                        }
                    }
                }.execute();
            }, acao_line);
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            Funcoes.acao_com_trava(() -> {
                tabela_news.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

                new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        Thread.sleep(300);
                        return null;
                    }

                    @Override
                    protected void done() {
                        try {
                            event_delete();
                            Log.registrarErro_noEx("[DELETE] - Linha excluída");
                        } finally {
                            acao_line.set(true); // 🔓 libera de novo
                            tabela_news.setCursor(Cursor.getDefaultCursor());
                            Log.registrarErro_noEx("[DELETE] - Linha não excluída");
                        }
                    }
                }.execute();
            }, acao_line);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // 2) NÃO está editando → tenta TRAVAR e entrar em edição
            int viewRowEditing = tabela_news.getSelectedRow();
            int viewColEditing = tabela_news.getSelectedColumn();

            // 🔹 AQUI ainda está o valor ANTIGO no model
            int modelRow = tabela_news.convertRowIndexToModel(viewRowEditing);
            int modelCol = tabela_news.convertColumnIndexToModel(viewColEditing);

            oldCellValue = tabela_news.getModel().getValueAt(modelRow, modelCol);
            oldCellRow = viewRowEditing;  // guardando em coordenada de VIEW
            oldCellCol = viewColEditing;
        }
    }//GEN-LAST:event_tabela_newsKeyPressed

    void event_delete() {
        int viewRow = tabela_news.getSelectedRow();
        int viewCol = tabela_news.getSelectedColumn();

        if (viewRow < 0 || viewCol < 0) {
            return;
        }

        delete_line(viewRow, viewCol);
    }

    void event_insert() {
        int viewRow = tabela_news.getSelectedRow();
        int viewCol = tabela_news.getSelectedColumn();

        if (viewRow < 0 || viewCol < 0) {
            return;
        }

        add_line(viewRow, viewCol);
    }

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if (wsClient != null) {
            try {
                wsClient.disconnectStomp();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            tabela_valores();
            tabela_tempo();
            att_producao();
        });

    }//GEN-LAST:event_formInternalFrameOpened

    void barra_titulo() {
        // Remove a barra de título, mas mantém a borda
        javax.swing.plaf.basic.BasicInternalFrameUI ui
                = (javax.swing.plaf.basic.BasicInternalFrameUI) getUI();
        ui.setNorthPane(null); // Remove a barra de título
        setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    void edicao_celula() {
        // Seleção por célula
        tabela_news.setCellSelectionEnabled(true);
        tabela_news.setSurrendersFocusOnKeystroke(true);
        tabela_news.putClientProperty("JTable.autoStartsEdit", Boolean.FALSE);

        // 🔁 Listener global de início/fim de edição (só precisa registrar UMA vez)
        tabela_news.addPropertyChangeListener("tableCellEditor", evt -> {
            Object newEditor = evt.getNewValue();
            if (newEditor instanceof TableCellEditor editor) {
                editor.addCellEditorListener(new javax.swing.event.CellEditorListener() {
                    @Override
                    public void editingStopped(javax.swing.event.ChangeEvent e) {
                        // edição confirmada (ENTER, clique fora, TAB, etc.)
                        onEditingFinished(true);
                    }

                    @Override
                    public void editingCanceled(javax.swing.event.ChangeEvent e) {
                        // edição cancelada (ESC)
                        onEditingFinished(false);
                    }
                });
            }
        });

        // ===== ENTER: iniciar edição OU finalizar edição =====
        InputMap im_enter = tabela_news.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am_enter = tabela_news.getActionMap();

        im_enter.put(KeyStroke.getKeyStroke("ENTER"), "start-or-commit-edit");
        am_enter.put("start-or-commit-edit", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {

                // 1) Se JÁ está editando → ENTER só faz COMMIT
                // (o unlock será disparado pelo CellEditorListener.editingStopped)
                if (tabela_news.isEditing()) {
                    TableCellEditor editor = tabela_news.getCellEditor();
                    if (editor != null) {
                        editor.stopCellEditing(); // aplica no model (dispara KeyReleased)
                    }
                    return;
                }

                // 2) NÃO está editando → tenta TRAVAR e entrar em edição
                int viewRow = tabela_news.getSelectedRow();
                int viewCol = tabela_news.getSelectedColumn();

                if (viewRow < 0 || viewCol < 0) {
                    return;
                }

                if (!tabela_news.isCellEditable(viewRow, viewCol)) {
                    return;
                }

                // VIEW -> MODEL
                int modelRow = tabela_news.convertRowIndexToModel(viewRow);
                int modelCol = tabela_news.convertColumnIndexToModel(viewCol);

                int sheetCol = modelCol; // ajusta se tiver coluna fake

                new Thread(() -> {
                    try {
                        System.out.printf("[ENTER] tentando lock row=%d col=%d%n", modelRow, sheetCol);
                        ApiClient.LockResult lockResult = api.tryLockCell(csv_server, modelRow, sheetCol);

                        if (!lockResult.granted) {
                            String dono = (lockResult.owner == null || lockResult.owner.isBlank())
                                    ? "outro usuário"
                                    : lockResult.owner;

                            SwingUtilities.invokeLater(() -> {
                                JOptionPane.showMessageDialog(
                                        tabela_news,
                                        "Esta célula está sendo editada por: " + dono,
                                        "Célula bloqueada",
                                        JOptionPane.WARNING_MESSAGE
                                );
                            });
                            return;
                        }

                        // LOCK OK → entra em edição na EDT
                        SwingUtilities.invokeLater(() -> {
                            lockedRow = modelRow;
                            lockedCol = sheetCol;
                            editingViewRow = viewRow;
                            editingViewCol = viewCol;
                            editingModelRow = modelRow;
                            editingModelCol = sheetCol;

                            tabela_news.editCellAt(viewRow, viewCol);
                            Component editor = tabela_news.getEditorComponent();
                            if (editor != null) {
                                editor.requestFocusInWindow();
                            }
                            System.out.printf("[ENTER] lock OK row=%d col=%d%n", modelRow, sheetCol);
                        });

                    } catch (Exception ex) {
                        ex.printStackTrace();
                        SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(
                                    tabela_news,
                                    "Erro ao tentar bloquear a célula.\n" + ex.getMessage(),
                                    "Erro de comunicação",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        });
                    }
                }).start();
            }
        });

        // ===== ESC: cancelar edição (voltar valor antigo) =====
        InputMap im_esc = tabela_news.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am_esc = tabela_news.getActionMap();

        im_esc.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancel-edit");

        am_esc.put("cancel-edit", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!tabela_news.isEditing()) {
                    return;
                }

                // ESC cancela a edição atual → valor volta ao que era antes
                // e dispara editingCanceled → onEditingFinished(false) → unlock
                TableCellEditor editor = tabela_news.getCellEditor();
                if (editor != null) {
                    editor.cancelCellEditing();
                }
            }
        });
    }

    private void restaurarValorAnteriorSeMesmaCelula(int viewRow, int viewCol) {
        if (oldCellRow == viewRow && oldCellCol == viewCol && oldCellValue != null) {
            tabela_news.setValueAt(oldCellValue, viewRow, viewCol);
        }
    }

    private void onEditingFinished(boolean committed) {
        final int row;
        final int col;

        // 🔒 Garante que só a PRIMEIRA chamada vai executar unlock
        synchronized (this) {
            if (editingModelRow < 0 || editingModelCol < 0) {
                // Já processamos/unlock está em andamento
                return;
            }

            // Captura os índices atuais
            row = editingModelRow;
            col = editingModelCol;

            // Já limpa o estado AQUI para evitar chamadas duplicadas
            clearEditingState();
        }

        System.out.printf("[EDITOR] finished committed=%s row=%d col=%d%n",
                committed, row, col);

        // Faz o unlock em background com os índices capturados
        new Thread(() -> {
            try {
                api.unlockCell(csv_server, row, col);
                System.out.println("[EDITOR] unlock OK row=" + row + " col=" + col);
            } catch (com.app.mirrorpage.client.net.ApiClient.ApiHttpException ex) {
                String msg = ex.getMessage();
                if (msg != null
                        && msg.contains("HTTP 403")
                        && msg.contains("Not lock owner")) {
                    // Já estava liberado / lock expirou / outra tentativa duplicada
                    System.out.println("[EDITOR] unlock 403 Not lock owner (já não havia lock). Ignorando.");
                } else {
                    System.err.println("[EDITOR] Erro HTTP ao desbloquear célula:");
                    ex.printStackTrace();
                }
            } catch (Exception ex) {
                System.err.println("[EDITOR] Erro inesperado ao desbloquear célula:");
                ex.printStackTrace();
            }
        }).start();
    }

    private void clearEditingState() {
        lockedRow = -1;
        lockedCol = -1;
        editingViewRow = -1;
        editingViewCol = -1;
        editingModelRow = -1;
        editingModelCol = -1;
    }

    public void in_tMat(int line, int column, boolean save) {
        int last_line = tabela_news.getRowCount() - 2;

        if (line == -1 || line == 0 || !(column == 8 || column == 9)) {
            return;
        }

        if (line == last_line) {
            System.out.println("Alerta de vadia");
            add_line(line, column);
        }

        Object tCab = tabela_news.getValueAt(line, 8);
        Object tVt = tabela_news.getValueAt(line, 9);

        int[] cab = parseMinSec(tCab);
        int[] vt = parseMinSec(tVt);

        int totalSeg = (cab[0] * 60 + cab[1]) + (vt[0] * 60 + vt[1]);

        String tMat;
        if (totalSeg > 3599) { // maior que 59:59
            tMat = "00:00";
            Tabela.celulasComErro.add(line);
        } else {
            int min = totalSeg / 60;
            int sec = totalSeg % 60;
            tMat = String.format("%02d:%02d", min, sec);
            Tabela.celulasComErro.remove(line);
        }

        tabela_news.setValueAt(tMat, line, 10);

        if (save) {
            sync.onCellEdit(line, 10, tMat);
        }

        if (listener != null) {
            listener.tempo_producao();
            listener.att_tempo();
            listener.stts_jornal();
        }

    }

    private int[] parseMinSec(Object val) {
        if (val == null || val.toString().isEmpty()) {
            return new int[]{0, 0};
        }
        String[] parts = val.toString().trim().split(":");
        int min = parts.length > 0 ? Funcoes.parseSafe(parts[0]) : 0;
        int sec = parts.length > 1 ? Funcoes.parseSafe(parts[1]) : 0;
        return new int[]{min, sec};
    }

    void add_tempo_entrada(int modelRow, int modelCol) {
        String valor = (String) tabela_news.getValueAt(modelRow, modelCol);
        if (valor != null) {
            if (listener != null) {
                listener.inicio_jornal(valor);
                listener.stts_jornal();
            }
        }

    }

    void add_tempo_encerramento(int modelRow, int modelCol) {
        String valor = (String) tabela_news.getValueAt(modelRow, modelCol);
        if (valor != null) {
            if (listener != null) {
                listener.tempo_encerramento(valor);
                listener.stts_jornal();
            }
        }
    }

    public void tempo_final(JTable table) {
        int total_lines = table.getRowCount();

        for (int c = 0; c < (total_lines - 2); c++) {
            String valor_tempo = (String) table.getValueAt(c, 13);

            String valor_tMat = (String) table.getValueAt(c, 10);
            valor_tMat = Funcoes.format_ms_to_hms(valor_tMat);

            String soma = Funcoes.soma_tempo(valor_tMat, valor_tempo);

            table.setValueAt(soma, (c + 1), 13);
        }
    }

    public void tempo_prelim_bo(JTable table) {
        int total_lines = table.getRowCount();

        for (int c = 1; c < (total_lines - 2); c++) {
            String valor_tempo = (String) table.getValueAt(c, 13);

            String valor_tMat = (String) table.getValueAt(c, 10);
            valor_tMat = Funcoes.format_ms_to_hms(valor_tMat);

            String soma = Funcoes.soma_tempo(valor_tMat, valor_tempo);
            table.setValueAt(soma, (c + 1), 13);
        }
    }

    public void tabela_valores() {
        String valor_in = (String) tabela_news.getValueAt(0, 13);

        int out = tabela_news.getRowCount() - 1;
        String valor_out = (String) tabela_news.getValueAt(out, 13);

        if (listener != null) {
            listener.inicio_jornal(valor_in);
            listener.tempo_encerramento(valor_out);
        }
    }

    public void tabela_tempo() {
        if (listener != null) {
            listener.tempo_producao();
            listener.att_tempo();
            listener.stts_jornal();
        }
    }

    void att_producao() {
        for (int row = 1; row < tabela_news.getRowCount() - 2; row++) {
            // usa a coluna 8 como base para recalcular
            in_tMat(row, 8, false);
        }
    }

    public void recalcularTodos_tMat() {
        int total = tabela_news.getRowCount();
        if (total < 3) {
            return;
        }

        int lastData = total - 2;

        for (int row = 1; row < lastData; row++) {
            in_tMat(row, 8, false);
        }
    }

    private void conectarWebSocket() {
        try {
            String wsUrl = api.getWebSocketUrl(); // ex: ws://host:8080/ws

            String topicId = csv_server
                    .replace("\\", "/")
                    .replace("/", "_");   // /BDBR/Final.csv → _BDBR_Final.csv

            String topic = "/topic/sheet/" + topicId;

            wsClient = new SheetSocketClient(
                    new URI(wsUrl),
                    topic,
                    this::onCellChangeEvent,
                    this::onRowInsertedEvent,
                    this::onRowMovedEvent,
                    this::onDeletedEvent
            );

            wsClient.connect(); // assíncrono

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("[WS] Falha ao conectar: " + e.getMessage());
        }
    }

    private void onCellChangeEvent(CellChangeEvent evt) {

        // Campos vindos do servidor
        final String path = evt.path;
        final int modelRow = evt.row;
        final int modelCol = evt.col;
        final String value = evt.value;
        final String user = evt.user;

        // 1) Garante que é desta planilha
        if (!csv_server.equals(path)) {
            return;
        }

        // 3) Atualizar JTable na EDT
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.table.TableModel model = tabela_news.getModel();

            if (modelRow < 0 || modelRow >= model.getRowCount()) {
                System.out.printf("[WS] row fora do limite: %d (rows=%d)%n",
                        modelRow, model.getRowCount());
                return;
            }
            if (modelCol < 0 || modelCol >= model.getColumnCount()) {
                System.out.printf("[WS] col fora do limite: %d (cols=%d)%n",
                        modelCol, model.getColumnCount());
                return;
            }

            // Se tiver sorter/filtro, converter MODEL -> VIEW
            int viewRow = tabela_news.convertRowIndexToView(modelRow);
            int viewCol = tabela_news.convertColumnIndexToView(modelCol);
            int last_row = tabela_news.getRowCount() - 1; // -1 = TOTAL, -1 = index

            if (viewRow < 0 || viewCol < 0) {
                System.out.printf("[WS] viewRow/viewCol inválidos: %d/%d%n", viewRow, viewCol);
                return;
            }

            System.out.printf(
                    "[WS] Aplicando mudança externa: path=%s row=%d col=%d value='%s' user=%s%n",
                    path, modelRow, modelCol, value, user
            );

            tabela_news.setValueAt(value, viewRow, viewCol);

            SwingUtilities.invokeLater(() -> {
                Tabela.ajustarLarguraColuna(tabela_news);

                if (viewCol == 8 || viewCol == 9) {
                    in_tMat(modelRow, modelCol, false);
                    return;
                }

                if (viewRow == 0 && viewCol == 13) {
                    add_tempo_entrada(viewRow, viewCol);
                    return;
                }

                if (viewRow == last_row && viewCol == 13) {
                    add_tempo_encerramento(viewRow, viewCol);
                    return;
                }
                // (Opcional) aqui dá pra fazer highlight na célula, etc.
            });

        });
    }

    private void onRowInsertedEvent(RowInsertedEvent ev) {
        if (!csv_server.equals(ev.path())) {
            return;
        }

        System.out.println("[WS] Linha inserida após: " + ev.afterRow());

        try {
            String csv = api.loadSheet(csv_server);

            SwingUtilities.invokeLater(() -> sync.aplicarCsvNoModelo(csv));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void onRowMovedEvent(RowMoveEvent ev) {
        // 1. Filtro de Caminho
        if (!csv_server.equals(ev.path())) {
            return;
        }

        System.out.println("[WS] Linha movida DE: " + ev.from() + " PARA: " + ev.to() + " - Quem: " + ev.user());

        try {
            String csv = api.loadSheet(csv_server);

            SwingUtilities.invokeLater(() -> sync.aplicarCsvNoModelo(csv));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void onDeletedEvent(RowDeletedEvent ev) {
        if (!csv_server.equals(ev.path())) {
            return;
        }

        System.out.println("[WS] Linha removida: " + ev.modelRow() + " Arquivo: " + ev.path() + " - Quem: " + ev.user());

        try {
            String csv = api.loadSheet(csv_server);

            SwingUtilities.invokeLater(() -> sync.aplicarCsvNoModelo(csv));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    void add_line(int viewRow, int viewCol) {
        if (viewRow < 0) {
            return; // nada selecionado
        }

        final DefaultTableModel modelo = (DefaultTableModel) tabela_news.getModel();
        int totalRows = modelo.getRowCount();
        if (totalRows == 0) {
            return;
        }

        // última linha de dados (penúltima da tabela: antes da TOTAL)
        int lastDataModelRow = Math.max(0, totalRows - 2);

        // VIEW -> MODEL
        int modelRow = tabela_news.convertRowIndexToModel(viewRow);

        // se o usuário estiver embaixo da última de dados (ex.: linha TOTAL),
        // força para usar a última linha de dados como "afterRow"
        if (modelRow > lastDataModelRow) {
            modelRow = lastDataModelRow;
        }

        // posição no model onde a nova linha será inserida
        int insertModelIndex = modelRow + 1;

        // ===== calcula num_pag = valor da linha anterior + 1 =====
        int numPag = 1;
        int prevRow = insertModelIndex - 1;
        if (prevRow >= 0 && prevRow < modelo.getRowCount()) {
            Object val = modelo.getValueAt(prevRow, 0);
            if (val != null) {
                try {
                    numPag = Integer.parseInt(val.toString().trim()) + 1;
                } catch (NumberFormatException e) {
                    // se não for número, mantém 1 (ou outro padrão se quiser)
                }
            }
        }

        // monta a linha vazia com seus padrões
        Object[] novaLinha = new Object[]{
            numPag, // primeira coluna = sequência
            "", "", "", "", "", "", "",
            "00:00", "00:00", "00:00",
            "", "", "00:00:00", ""
        };

        // 1) insere visualmente na tabela
        modelo.insertRow(insertModelIndex, novaLinha);

        sync.onInsertRow(modelRow);

        selecao_line(viewRow, viewCol);

    }

    void move_line(int viewRow, int viewCol, int rowDestView) {
        if (viewRow < 0) {
            return;
        }

        final DefaultTableModel modelo = (DefaultTableModel) tabela_news.getModel();

        // Converte para índices do modelo (dados reais)
        int modelRow = tabela_news.convertRowIndexToModel(viewRow);
        int rowDestModel = tabela_news.convertRowIndexToModel(rowDestView);

        // =================================================================
        // 🔒 BLOQUEIO DA LINHA 0 FIXA
        // =================================================================
        // Regra 1: A Linha 0 não sai do lugar
        if (modelRow == 0) {
            System.out.println("Bloqueado: A linha 0 é fixa.");
            restaurarValorAnteriorSeMesmaCelula(viewRow, viewCol); // Se tiver lógica de drag visual
            return;
        }

        // Regra 2: Nenhuma linha pode ocupar o lugar da Linha 0
        if (rowDestModel == 0) {
            System.out.println("Bloqueado: Não pode mover para a posição 0.");
            restaurarValorAnteriorSeMesmaCelula(viewRow, viewCol);
            return;
        }

        // =================================================================
        // 🔒 BLOQUEIO DO RODAPÉ
        // =================================================================
        int lastDataModelRow = modelo.getRowCount() - 2; // -1 é Rodapé, -2 é último dado móvel

        if (modelRow > lastDataModelRow || rowDestModel > lastDataModelRow) {
            restaurarValorAnteriorSeMesmaCelula(viewRow, viewCol);
            return; // Protege rodapé
        }

        // Se passar daqui, o movimento é VÁLIDO (ex: Row 1 -> Row 4)
        if (rowDestModel != modelRow) {
            modelo.moveRow(modelRow, modelRow, rowDestModel);

            // Envia para o servidor:
            // Path, from=1, to=4
            // O servidor vai calcular: realFrom=2, realTo=5 (Ok!)
            sync.onTrocarLine(modelRow, rowDestModel, usuarioLogado);

            // Mantém a seleção visual na nova posição
            selecao_line(rowDestView, viewCol);
        }

        // Limpeza de variáveis de controle de drag
        oldCellValue = null;
        oldCellRow = -1;
        oldCellCol = -1;
    }

    void delete_line(int viewRow, int viewCol) {
        if (viewRow < 0) {
            return;
        }
        // 2. Converte para índice do Modelo (caso a tabela esteja ordenada/filtrada)
        int modelRow = tabela_news.convertRowIndexToModel(viewRow);
        int totalRows = tabela_news.getModel().getRowCount();

        // --- REGRAS DE PROTEÇÃO (IGUAIS AO SERVIDOR) ---
        // Regra A: A Linha 0 (Fixa) não pode ser apagada
        if (modelRow == 0) {
            return;
        }

        // Regra B: O Rodapé não pode ser apagado
        // A última linha (index = totalRows - 1) é o rodapé
        if (modelRow >= totalRows - 1) {
            return;
        }

        // 3. Confirmação do Usuário
        int confirm = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir a linha " + (modelRow) + "?\nEsta ação não pode ser desfeita.",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        sync.onDeleteLine(modelRow);

        selecao_line(viewRow - 1, viewCol);

    }

    void selecao_line(int viewRow, int viewCol) {
        // 2) informa o servidor: afterRow = modelRow (linha de dados DEPOIS da qual
        SwingUtilities.invokeLater(() -> {
            int mRow = tabela_news.convertRowIndexToModel(viewRow);
            int mCol = tabela_news.convertColumnIndexToModel(viewCol);
            tabela_news.setRowSelectionInterval(mRow, mRow);
            tabela_news.setColumnSelectionInterval(mCol, mCol);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabela_news;
    // End of variables declaration//GEN-END:variables

}
