package com.app.mirrorpage.ui;

import com.app.mirrorpage.app.framework.Log;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

public class Login extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/logo.png"));

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        field_usuario.setText("admin");
        field_senha.setText("Admin@2025");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        field_usuario = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        field_servidor = new javax.swing.JTextField();
        field_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));
        setIconImage(icon.getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Globotipo Corporativa Textos", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mirror Page");

        jLabel2.setFont(new java.awt.Font("Globotipo Corporativa Textos", 1, 14)); // NOI18N
        jLabel2.setText("Servidor:");

        jLabel3.setFont(new java.awt.Font("Globotipo Corporativa Textos", 1, 14)); // NOI18N
        jLabel3.setText("Usuário");

        jLabel4.setFont(new java.awt.Font("Globotipo Corporativa Textos", 1, 14)); // NOI18N
        jLabel4.setText("Senha");

        btn_login.setText("Logar");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_login)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_usuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_senha))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        String baseUrlInput = field_servidor.getText().trim();
        if (baseUrlInput.isEmpty()) {
            baseUrlInput = "http://localhost:8080";
        }

        String user = field_usuario.getText().trim();
        char[] passArr = field_senha.getPassword();

        String baseUrl;
        try {
            baseUrl = normalizeBaseUrl(baseUrlInput);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Endereço do servidor inválido.\nDica: use algo como http(s)://host[:porta][/caminho]",
                    "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (user.isEmpty() || passArr.length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe usuário e senha.",
                    "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        btn_login.setEnabled(false);
        setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));

        final String pass = new String(passArr);      // necessário para JSON
        java.util.Arrays.fill(passArr, '\0');         // higiene

        new javax.swing.SwingWorker<com.app.mirrorpage.app.framework.Session, Void>() {
            @Override
            protected com.app.mirrorpage.app.framework.Session doInBackground() throws Exception {
                // NUNCA UI aqui
                var auth = new com.app.mirrorpage.client.net.AuthClient(baseUrl);
                var res = auth.login(user, pass); // pode lançar exceções específicas
                return new com.app.mirrorpage.app.framework.Session(
                        baseUrl, res.accessToken, res.refreshToken, user, res.roles);
            }

            @Override
            protected void done() {
                try {
                    var session = get(); // pode lançar ExecutionException

                    Log.registrarErro_noEx("Entrada de usuário: " + user);
                    dispose();

                    var principal = new com.app.mirrorpage.ui.Principal(session);
                    principal.paint_tema();

                    SwingUtilities.invokeLater(() -> {
                        principal.setVisible(true);
                    });

                } catch (java.util.concurrent.CancellationException e) {
                    showInfo("Operação cancelada.");

                } catch (java.util.concurrent.ExecutionException e) {
                    handleLoginFailure(e.getCause(), baseUrl);

                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    showError("Operação interrompida.");

                } finally {
                    // Centraliza “limpeza” de estado da UI
                    btn_login.setEnabled(true);
                    setCursor(java.awt.Cursor.getDefaultCursor());
                }
            }

            private void showInfo(String msg) {
                javax.swing.JOptionPane.showMessageDialog(Login.this,
                        msg, "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

            private void showError(String msg) {
                javax.swing.JOptionPane.showMessageDialog(Login.this,
                        msg, "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            private void handleLoginFailure(Throwable cause, String normalizedBase) {
                String msg;
                if (cause instanceof com.app.mirrorpage.client.net.AuthClient.AuthException) {
                    msg = "Credenciais inválidas. Confira usuário/senha.";
                } else if (cause instanceof javax.net.ssl.SSLHandshakeException
                        || cause instanceof java.security.cert.CertificateException) {
                    msg = "Falha SSL/TLS ao conectar em " + normalizedBase
                            + ". Verifique o certificado (HTTPS).";
                } else if (cause instanceof java.net.UnknownHostException) {
                    msg = "Servidor não encontrado (" + normalizedBase + ")."
                            + " Verifique o endereço (DNS) e sua conexão.";
                } else if (cause instanceof java.net.ConnectException) {
                    msg = "Não foi possível conectar ao servidor (" + normalizedBase
                            + "). Porta fechada ou serviço indisponível.";
                } else if (cause instanceof java.net.SocketTimeoutException) {
                    msg = "Tempo de conexão excedido (timeout). Tente novamente.";
                } else if (cause instanceof java.io.IOException) {
                    msg = "Falha de rede: " + cause.getMessage();
                } else if (cause instanceof InterruptedException) {
                    Thread.currentThread().interrupt();
                    msg = "Operação interrompida. Tente novamente.";
                } else {
                    msg = "Falha no login: " + (cause != null ? cause.getMessage() : "erro desconhecido");
                }
                showError(msg);
            }
        }.execute();
    }

    /**
     * Normaliza a base URL: - Garante esquema http/https (preserva se
     * informado). - Remove apenas uma barra final (se houver). - Valida
     * host/porta e caminho.
     */
    private static String normalizeBaseUrl(String input) {
        String u = input.trim();

        // Se não tem esquema, assume http
        if (!u.matches("^(?i)https?://.*")) {
            u = "http://" + u;
        }

        try {
            java.net.URI uri = java.net.URI.create(u);

            if (uri.getHost() == null) { // cobre casos como "http:///..."
                throw new IllegalArgumentException("Host ausente");
            }

            // Reconstrói sem barra final redundante
            String path = uri.getPath();
            if (path != null && path.length() > 1 && path.endsWith("/")) {
                path = path.substring(0, path.length() - 1);
            }

            java.net.URI cleaned = new java.net.URI(
                    uri.getScheme(),
                    uri.getUserInfo(),
                    uri.getHost(),
                    uri.getPort(),
                    path,
                    uri.getQuery(),
                    uri.getFragment()
            );

            return cleaned.toString();

        } catch (IllegalArgumentException | java.net.URISyntaxException ex) {
            throw new IllegalArgumentException("URL inválida", ex);
        }


    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPasswordField field_senha;
    private javax.swing.JTextField field_servidor;
    private javax.swing.JTextField field_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
